version: '3.8'

services:
  # Локальный PostgreSQL для разработки
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: query_analyzer
      POSTGRES_USER: analyzer_user
      POSTGRES_PASSWORD: analyzer_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c pg_stat_statements.max=10000

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://analyzer_user:analyzer_pass@postgres:5432/query_analyzer
      OPENAI_API_KEY: your_openai_api_key_here
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

volumes:
  postgres_data: